// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhtrIuYZTKZBh7oiP6Silgs8Y9UxjViWs',
    appId: '1:432558263570:android:34510791efbf281c6337cb',
    messagingSenderId: '432558263570',
    projectId: 'kigali-city-services-64e57',
    storageBucket: 'kigali-city-services-64e57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN81Tsl5uHTG-E3egGuq2BEpUcgSUMWfE',
    appId: '1:432558263570:ios:3ad1e280cf9805726337cb',
    messagingSenderId: '432558263570',
    projectId: 'kigali-city-services-64e57',
    storageBucket: 'kigali-city-services-64e57.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServicesAndPlaces',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMFBaEiKPbcefFSqjHZbLxIBKD0LezX0Y',
    appId: '1:432558263570:web:61ff64d1131518796337cb',
    messagingSenderId: '432558263570',
    projectId: 'kigali-city-services-64e57',
    authDomain: 'kigali-city-services-64e57.firebaseapp.com',
    storageBucket: 'kigali-city-services-64e57.firebasestorage.app',
  );

}